---
title: "01_data"
author: "Sglatt"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Github
```{r git, eval=FALSE}
usethis::create_from_github("https://github.com/Sfglatt/plf-telehealth-eval.git",
  destdir = "~/Github/plf-telehealth-eval"
)
```

```{r packages}
if (!require("dplyr")) {
  install.packages("dplyr")
  require("dplyr")
}
if (!require("psych")) {
  install.packages("psych")
  require("psych")
}
if (!require("readxl")) {
  install.packages("readxl")
  require("readxl")
}
if (!require("stringr")) {
  install.packages("stringr")
  require("stringr")
}
if (!require("tidyverse")) {
  install.packages("tidyverse")
  require("tidyverse")
}
```

```{r folder to save output}
if (!dir.exists("01_Output")) {
  dir.create("01_Output")
}
```

```{r Data}
# Raw data in separate tabs
path <- "~/Labs/Github/project-life-force/project-life-force/Raw_datasets/database_12-29-2024.xlsx"
excel_sheets(path)

# This tab has lifetime SA information. Month = -9 is lifetime.
csrss <- read_excel(path, sheet = "cssrs")

# Make a variable for C-SSRS month = -9
csrss <- csrss %>%
  group_by(id) %>%
  mutate(q11_CSSRS_lifetime = q11[month == -9]) %>%
  ungroup()

# Recode No (2) as 0
csrss <- csrss %>%
  mutate(q11_CSSRS_lifetime = ifelse(q11_CSSRS_lifetime == 2, 0, q11_CSSRS_lifetime))

# This tab has sessions data
sessions <- read_excel(path, sheet = "sessions")
colnames(sessions) <- gsub("\\s+", "_", colnames(sessions))

# Verify the number of participants
length(unique(sessions$id)) # N = 101
```

# Original attendance variable 
```{r session attendance}
# Make a 'total number of sessions attended' variable.
# Add up the number of dates they attended (the *number* of unique dates per person for a total session count)

sessions <- sessions %>%
  group_by(id) %>%
  mutate(n_new = if_else(arm == 1, sum(!is.na(date)), NA))

# Make a "treatment engaged" and "treatment completed" variables based on the number of sessions they attended
sessions$initiated <- ifelse(sessions$n_new > 0, 1, 0)
sessions$six_sess <- ifelse(sessions$n_new > 5, 1, 0)
sessions$completer <- ifelse(sessions$n_new >= 10, 1, 0)

# Make a single variable for all
sessions <- sessions %>%
  mutate(
    Attendance = case_when(
      completer == 1 ~ "Completer",
      six_sess == 1 ~ "Six Sessions",
      initiated == 1 ~ "Initiated",
      TRUE ~ "Did not initiate"
    )
  )

# Look at modality
table(unique(sessions[c("id", "type")])$type)

# 1	In-person (n = 22)
# 2	Telehealth (n = 44)
# 3	Both (n = 4)
# People who attended 0 sessions are not coded

# Make another modality type variable with "both" included in "telehealth"
sessions$type_new <- sessions$type
sessions$type_new[sessions$type_new == 3] <- 2
sessions$type_new[sessions$type_new == 1] <- 0
sessions$type_new[sessions$type_new == 2] <- 1

# Replace NA (i.e., missing type) with 0 for non-attenders (for both the original site and site_new)
sessions$type_NA <- sessions$type
sessions$type_NA[is.na(sessions$type)] <- 0

sessions$type_new_NA <- sessions$type_new
sessions$type_new_NA[is.na(sessions$type_new)] <- 0

# Confirm the changes
table(unique(sessions[c("id", "type_new")])$type_new)
table(unique(sessions[c("id", "type_new_NA")])$type_new_NA)
```

# New session attendance
```{r session attendance new}
# New sessions column with changed format
sessions <- sessions %>%
  mutate(
    sessn_dup = tolower(sessn), # duplicate + lowercase
    sessn_dup = trimws(sessn_dup),

    # remove text ONLY if it follows a number + space (e.g., "session 5 cont". but "5a" stays the same)
    sessn_dup = gsub("(\\d)\\s+cont.*$", "\\1", sessn_dup)
  )

# Put sessn_dup next to sessn on the right
# Verify
View(sessions) # Good.

# duplicates within person
# same id + same cleaned session
dup_sessions <- sessions %>%
  group_by(id, sessn_dup) %>%
  filter(n() > 1) %>%
  arrange(id, sessn_dup)

dup_sessions

# new session count excluding duplicates
sessions <- sessions %>%
  group_by(id) %>%
  mutate(
    n_new_noduplicates = n_distinct(sessn_dup[!is.na(date) & arm == 1])
  )

# New initiator/engaged/completer variables
sessions <- sessions %>%
  mutate(
    initiated_nodup = ifelse(n_new_noduplicates > 0, 1, 0),
    six_sess_nodup  = ifelse(n_new_noduplicates > 5, 1, 0),
    completer_nodup = ifelse(n_new_noduplicates >= 10, 1, 0)
  )

# New counts
person_level <- sessions %>%
  group_by(id) %>%
  summarise(
    n_new = first(n_new),
    n_new_noduplicates = first(n_new_noduplicates),
    initiated = first(initiated),
    initiated_nodup = first(initiated_nodup),
    six_sess = first(six_sess),
    six_sess_nodup = first(six_sess_nodup),
    completer = first(completer),
    completer_nodup = first(completer_nodup)
  )

summary(person_level$n_new)
summary(person_level$n_new_noduplicates)

# Initiated
sum(person_level$initiated, na.rm = TRUE)
sum(person_level$initiated_nodup, na.rm = TRUE)

# 6+ sessions
sum(person_level$six_sess, na.rm = TRUE)
sum(person_level$six_sess_nodup, na.rm = TRUE)

# Completed (10 sessions)
sum(person_level$completer, na.rm = TRUE)
sum(person_level$completer_nodup, na.rm = TRUE)

# Rearrange so new comes after each old
sessions <- sessions %>%
  relocate(
    sessn_dup,
    .after = sessn
  ) %>%
  relocate(
    n_new_noduplicates,
    .after = n_new
  ) %>%
  relocate(
    initiated_nodup,
    .after = initiated
  ) %>%
  relocate(
    six_sess_nodup,
    .after = six_sess
  ) %>%
  relocate(
    completer_nodup,
    .after = completer
  )

# Dataframe of people with duplicates
dup_id <- dup_sessions %>%
  distinct(id)

sessions_dup_ids <- sessions %>%
  filter(id %in% dup_id$id) # dataframe of people with >0 duplicate session

# Session descriptions with only text (no numbers)
# Sessions labeled with "misc" or "review":
sessions <- sessions %>%
  mutate(
    misc_review = grepl("misc|review", sessn) & !is.na(sessn)
  )

# Look at them
sessions_miscreview <- sessions %>%
  filter(misc_review)
sessions_miscreview

# Expand to session description with no numbers
sessions <- sessions %>%
  mutate(
    only_text = !grepl("[0-9]", sessn) & !is.na(sessn)
  )

# Look at them
sessions_only_text <- sessions %>%
  filter(only_text)

sessions_only_text

# Get their IDs
sessions_text_ids <- sessions %>%
  group_by(id) %>%
  filter(any(!is.na(sessn) & !grepl("[0-9]", sessn))) %>%
  ungroup()
sessions_text_ids

# How many people?
sessions %>%
  filter(!is.na(sessn) & !grepl("[0-9]", sessn)) %>%
  summarise(n_ids = n_distinct(id)) # 15

# New count with no duplicates (as above) & no free-text sessions identified above
sessions <- sessions %>%
  group_by(id) %>%
  mutate(
    n_new_noduplicatestext = n_distinct(
      sessn_dup[!is.na(date) & arm == 1 & !only_text]
    )
  )

sessions <- sessions %>%
  mutate(
    initiated_clean = ifelse(n_new_noduplicatestext > 0, 1, 0),
    six_sess_clean  = ifelse(n_new_noduplicatestext > 5, 1, 0),
    completer_clean = ifelse(n_new_noduplicatestext >= 10, 1, 0)
  )

person_level <- sessions %>%
  group_by(id) %>%
  summarise(
    n_new = first(n_new),
    n_new_noduplicates = first(n_new_noduplicates),
    n_clean = first(n_new_noduplicatestext),
    initiated = first(initiated),
    initiated_nodup = first(initiated_nodup),
    initiated_clean = first(initiated_clean),
    six_sess = first(six_sess),
    six_sess_nodup = first(six_sess_nodup),
    six_sess_clean = first(six_sess_clean),
    completer = first(completer),
    completer_nodup = first(completer_nodup),
    completer_clean = first(completer_clean)
  )

summary(person_level$n_new)
summary(person_level$n_new_noduplicates)
summary(person_level$n_clean)

table(person_level$n_new)
table(person_level$n_new_noduplicates)
table(person_level$n_clean)

# Compare drops
sum(person_level$completer, na.rm = TRUE)
sum(person_level$completer_nodup, na.rm = TRUE)
sum(person_level$completer_clean, na.rm = TRUE)

sum(person_level$six_sess, na.rm = TRUE)
sum(person_level$six_sess_nodup, na.rm = TRUE)
sum(person_level$six_sess_clean, na.rm = TRUE)

# Make a new single variable for all
sessions <- sessions %>%
  mutate(
    Attendance_clean = case_when(
      completer_clean == 1 ~ "Completer",
      six_sess_clean == 1 ~ "Six Sessions",
      initiated_clean == 1 ~ "Initiated",
      TRUE ~ "Did not initiate"
    )
  )
```

# Self-report/clinical assessment data 
```{r self-report}
# Combined self-report data
plf_data <- read.csv("~/Labs/Github/project-life-force/project-life-force/01_Created_datasets/Merged_plf_data_filtered_2025-04-09.csv")

# Look at site n's
table(plf_data[plf_data$month == 0, ]$site)

# Combine Northport (n = 2) and Bronx participants
plf_data <- plf_data %>%
  group_by(id) %>%
  tidyr::fill(site, .direction = "downup") %>%
  ungroup()

plf_data <- plf_data %>%
  mutate(
    site_new = site,
    site_new = ifelse(site_new == 2, 1, site_new)
  )

# Confirm
table(plf_data[plf_data$month == 0, ]$site)
table(plf_data[plf_data$month == 0, ]$site_new)

# Make a labeled arm variable
plf_data <- plf_data %>%
  dplyr::mutate(arm_label = ifelse(arm_rec == 1, "PLF", "TAU"))
```

# Add session attendance to self-report
```{r self-report sessions}
# Add n_sessions_attended and modality_type_new
plf_data$n_sessions_attended <- sessions$n_new[match(plf_data$id, sessions$id)]
plf_data$modality_type <- sessions$type[match(plf_data$id, sessions$id)]
plf_data$modality_type_new <- sessions$type_new[match(plf_data$id, sessions$id)]
plf_data$completer <- sessions$completer[match(plf_data$id, sessions$id)]
plf_data$six_sess <- sessions$six_sess[match(plf_data$id, sessions$id)]
plf_data$initiated <- sessions$initiated[match(plf_data$id, sessions$id)]
plf_data$Attendance <- sessions$Attendance[match(plf_data$id, sessions$id)]

# Add the new attendance variables - n_new_noduplicatestext, initiated_clean, six_sess_clean, completer_clean
plf_data$n_sessions_attended_clean <- sessions$n_new_noduplicatestext[match(plf_data$id, sessions$id)]
plf_data$initiated_clean <- sessions$initiated_clean[match(plf_data$id, sessions$id)]
plf_data$six_sess_clean <- sessions$six_sess_clean[match(plf_data$id, sessions$id)]
plf_data$completer_clean <- sessions$completer_clean[match(plf_data$id, sessions$id)]
plf_data$Attendance_clean <- sessions$Attendance_clean[match(plf_data$id, sessions$id)]
```

# Add lifetime C-SSRS to self-report
```{r self-report cssrs}
# Add the lifetime C-SSRS
plf_data$q11_CSSRS_lifetime <- csrss$q11_CSSRS_lifetime[match(plf_data$id, csrss$id)]
```

# Filter the data to PLF arm and >0 sessions
```{r filter data}
# Filter the dataset to PLF and >0 sessions
plf_data_filtered <- plf_data %>%
  filter(
    arm_label == "PLF",
    n_sessions_attended_clean > 0,
    month != -9
  )
```

# How many total were randomzed to telehealth/in-person/both
```{r plf numbers}
# How many don't have a modality logged
unique(sessions$id[is.na(sessions$type) | sessions$type == ""]) # 31

# Look at their data
sessions[is.na(sessions$type) | sessions$type == "", ]

# Look at their date of consent
dates <- read_excel(path, sheet = "status")
# dtcon, dtcm00

# Look at the data for people who are missing modality type
missing_modality_ids <- unique(sessions$id[is.na(sessions$type) | sessions$type == ""])
dates[dates$id %in% missing_modality_ids, ]

# The breakdown in the sessions data for PLF
table(plf_data[plf_data$arm_rec == 1 & plf_data$month == 0, ]$modality_type)

# The breakdown in the dates data for PLF
table(dates[dates$arm == 1, ]$tele)
# 40 in-person, 55 telehealth, 6 mixed

# From this dates data, include people who initiated treatment in PLF
dates_initiated <- dates %>%
  filter(id %in% sessions$id[sessions$initiated == 1])
view(dates_initiated)

# The breakdown in the dates data
table(dates_initiated$arm, dates_initiated$tele)

# Check that they concord
common_ids <- intersect(dates$id, sessions$id)
dates_sub <- dates[dates$id %in% common_ids, c("id", "tele")]
sessions_sub <- sessions[sessions$id %in% common_ids, c("id", "type")]
comparison <- merge(dates_sub, sessions_sub, by = "id")
all_match <- all(comparison$tele == comparison$type)
mismatched_ids <- comparison$id[comparison$tele != comparison$type]

# There is one person characterized as mixed in the "status" tab and "in-person" in the sessions tab. Check who:
intersect(
  dates$id[dates$tele == "3"],
  sessions$id[sessions$type == "1"]
)

# 083. Look at their data in the sessions vs dates tab
sessions[sessions$id == "BX-083", ]
dates[dates$id == "BX-083", ]
# MG resolution: this person was in-person

# From this dates data, exclude people who initiated treatment
dates_exclude <- dates %>%
  filter(id %in% sessions$id[sessions$n_attended == 0])

# The breakdown in the dates data
table(dates_exclude$arm, dates_exclude$tele)

# Who is mixed in the tele variable here?
dates_exclude$id[dates_exclude$tele == "3"] # 085

# Look at their data
sessions[sessions$id == "BX-085", ]
dates[dates$id == "BX-085", ]
# They were randomized to in-person (Jan 2020), but never attended any sessions.

# Make their tele variable from 3 to 1 in the full dates data
dates$tele[dates$id == "BX-085"] <- "1"
dates$tele[dates$id == "BX-083"] <- "1"
```

# Save data for MLMs
```{r save mlm data, eval=TRUE}
write.csv(
  plf_data_filtered,
  paste0("01_Output/treatment_data_sg_", Sys.Date(), ".csv")
)
# 2025-10-21: First filtered multi-wave data
# 2025-12-15: Add C-SSRS
# 2026-01-12: Make/add new attendance variable
# 2026-05-12: (Re)tabulate attendance variables with different logic
```

# Save data for ITT engagement/initiation
```{r save itt data, eval=TRUE}
# From the dates sheet, make a modality assignment variable
dates <- dates %>%
  mutate(
    modality_assign = case_when(
      tele == "1" ~ 0, # in-person
      tele == "2" ~ 1, # telehealth
      tele == "3" ~ 0, # in person and shifted to telehealth - in person for ITT (all assigned in-person)
    )
  )

table(dates$modality_assign, useNA = "ifany")

# Merge modality assignment (ITT) into the dataset
plf_data <- plf_data %>%
  left_join(
    dates %>% dplyr::select(id, modality_assign),
    by = "id"
  )

# Filter to baseline and the PLF arm
plf_data_m0_plf <- plf_data %>%
  dplyr::filter(month == 0, arm_rec == 1)

table(plf_data_m0_plf$modality_assign, useNA = "ifany") # 0 = telehealth, 46; 1 = in-person, 55

# Save data
write.csv(
  plf_data_m0_plf,
  paste0("01_Output/initiation_data_sg_", Sys.Date(), ".csv")
)
# 2026-01-02: First filtered ITT data for initiation/engagement
# 2026-01-12: Make/add new attendance variable
# 2026-05-12: (Re)tabulate attendance variables with different logic
```

