---
title: "02_descriptives"
author: "Sglatt"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
if (!require("tidyr")) {
  install.packages("tidyr")
  require("tidyr")
}
if (!require("dplyr")) {
  install.packages("dplyr")
  require("dplyr")
}
if (!require("psych")) {
  install.packages("psych")
  require("psych")
}
if (!require("janitor")) {
  install.packages("janitor")
  require("janitor")
}
```

```{r folder to save output}
if (!dir.exists("02_Output")) {
  dir.create("02_Output")
}
```

# Data
Created in 01_data.Rmd
```{r data}
# Stratified sample
plf_data_filtered <- read.csv("01_Output/treatment_data_sg_2025-10-21.csv")

# Filter to pre and post treatment
plf_data_treatment <- plf_data_filtered %>%
  filter(month %in% c(0, 3, 6, 12))

# Remove mixed-modal participants
plf_data_treatment_sens <- plf_data_treatment %>%
  filter(modality_type != 3)

# Make a baseline dataset
plf_data_baseline <- plf_data_filtered %>%
  filter(month == 0)

# Remove mixed-modal participants from baseline dataset
plf_data_baseline_sens <- plf_data_baseline %>%
  filter(modality_type != 3)

# ITT baseline sample
plf_data_itt <- read.csv("01_Output/initiation_data_sg_2026-01-02.csv")
```

# Sample N descriptives
```{r sample}
# Modality
table(plf_data_baseline$modality_type)
table(plf_data_baseline_sens$modality_type)

# VA Site
table(plf_data_baseline$site)

# Modality + Site
table(
  plf_data_baseline$site,
  plf_data_baseline$modality_type
)
```

# Descriptives for outcomes per group and pre/post
```{r descriptives}
plf_data_treatment_descriptives <- plf_data_treatment_sens %>%
  dplyr::select(modality_type_new, month, srcs17, srcse, srcsi)

months_to_include <- c(0, 3, 6, 12)

# Function for tidier results
describe_tidy <- function(data, modality_label) {
  desc_list <- psych::describeBy(data[, -c(1, 2)], group = data$month, mat = FALSE)
  desc_list <- desc_list[names(desc_list) %in% as.character(months_to_include)]

  # make a tidy table
  bind_rows(lapply(names(desc_list), function(m) {
    tbl <- desc_list[[m]]
    tbl %>%
      mutate(
        Month = m,
        Modality = modality_label,
        `Mean (SD)` = sprintf("%.2f (%.2f)", mean, sd),
        `Median [Range]` = sprintf("%.2f [%.2f - %.2f]", median, min, max)
      ) %>%
      select(vars, Month, Modality, n, `Mean (SD)`, `Median [Range]`, skew, kurtosis)
  }))
}

# Descriptives for full sample and statified by modality
full_tidy <- describe_tidy(plf_data_treatment_descriptives, "Full")
ip_tidy <- describe_tidy(filter(plf_data_treatment_descriptives, modality_type_new == 0), "In-person")
th_tidy <- describe_tidy(filter(plf_data_treatment_descriptives, modality_type_new == 1), "Telehealth")

# Combine all
prepost_all_tidy <- bind_rows(full_tidy, ip_tidy, th_tidy)

# Save CSV
write.csv(prepost_all_tidy,
  file = paste0("02_Output/pre_post_descriptives_sg_", format(Sys.Date(), "%Y-%m-%d"), ".csv"),
  row.names = FALSE
)
```

# Check for any model covariates
Chi and Fisher's exact test between lifetime suicide attempt and modality. 
```{r lifetime attempt chi 1}
# Cross-tabulate lifetime suicide attempt history
Table_1 <- plf_data_baseline_sens %>%
  tabyl(q11_CSSRS_lifetime, modality_type) %>%
  adorn_totals(where = c("row", "col")) %>%
  adorn_percentages("col") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns()

Table_1

# Chi-square, mlm sample
chi_square_result_mlm <- chisq.test(
  plf_data_baseline_sens$q11_CSSRS_lifetime,
  plf_data_baseline_sens$modality_type_new
)

# Fisher's exact test, mlm sample
fisher_result_mlm <- fisher.test(
  plf_data_baseline_sens$q11_CSSRS_lifetime,
  plf_data_baseline_sens$modality_type_new
)

# Actual and expected frequencies, mlm sample
sjPlot::tab_xtab(
  var.row = plf_data_baseline_sens$q11_CSSRS_lifetime,
  var.col = plf_data_baseline_sens$modality_type_new,
  title = "Contingency Table MLM",
  show.row.prc = TRUE,
  show.col.prc = TRUE,
  show.summary = TRUE,
  statistics = "pearson",
  show.exp = TRUE,
  show.legend = TRUE
)


# Chi-square, itt sample
chi_square_result_itt <- chisq.test(
  plf_data_itt$q11_CSSRS_lifetime,
  plf_data_itt$modality_assign
)

# Fisher's exact test, itt sample
fisher_result_itt <- fisher.test(
  plf_data_itt$q11_CSSRS_lifetime,
  plf_data_itt$modality_assign
)

# Actual and expected frequencies, itt sample
sjPlot::tab_xtab(
  var.row = plf_data_itt$q11_CSSRS_lifetime,
  var.col = plf_data_itt$modality_assign,
  title = "Contingency Table ITT",
  show.row.prc = TRUE,
  show.col.prc = TRUE,
  show.summary = TRUE,
  statistics = "pearson",
  show.exp = TRUE,
  show.legend = TRUE
)

report::report(chi_square_result_mlm)
report::report(chi_square_result_itt)
```

# Suicidal ideation, depression symptom severity, etc
Descriptives and t-tests 
```{r covariates}
# Isolate data
covariates_mlm <- plf_data_baseline_sens %>%
  dplyr::select(
    modality_type_new,
    bdi, bhs, ssi, inq_pb, inq_tb, srcs17,
    Number_MH_encounters,
    age_demo
  )

covariates_itt <- plf_data_itt %>%
  dplyr::select(
    modality_assign,
    bdi, bhs, ssi, inq_pb, inq_tb, srcs17,
    Number_MH_encounters,
    age_demo
  )


# Look at descriptive tables, main mlm sample
covariates_mlm <- psych::describeBy(covariates_mlm[, -1], covariates_mlm$modality_type_new)
in_person_table_mlm <- covariates_mlm$"0"
telehealth_table_mlm <- covariates_mlm$"1"

in_person_table_mlm
telehealth_table_mlm

# Look at descriptive tables, ITT sample (modality assignment variable)
covariates_itt <- psych::describeBy(covariates_itt[, -1], covariates_itt$modality_assign)
in_person_table_itt <- covariates_itt$"0"
telehealth_table_itt <- covariates_itt$"1"

in_person_table_itt
telehealth_table_itt

# t-tests for main mlm sample
t_test_covariates_mlm <- plf_data_baseline_sens %>%
  rempsyc::nice_t_test(
    response = c("ssi", "bdi", "bhs", "inq_tb", "inq_pb", "srcs17", "bpaqpa", "bpaqva", "Number_MH_encounters", "age_demo"),
    group = "modality_type_new"
  )

t_test_covariates_mlm

# t-tests for itt sample
t_test_covariates_itt <- plf_data_itt %>%
  rempsyc::nice_t_test(
    response = c("ssi", "bdi", "bhs", "inq_tb", "inq_pb", "srcs17", "bpaqpa", "bpaqva", "Number_MH_encounters", "age_demo"),
    group = "modality_assign"
  )

t_test_covariates_itt


# Check baseline correlations between suicide-related coping & suicidal ideation
cor.test(plf_data_baseline_sens$ssi, plf_data_baseline_sens$srcs17)
cor.test(plf_data_baseline_sens$ssi, plf_data_baseline_sens$srcse)
cor.test(plf_data_baseline_sens$ssi, plf_data_baseline_sens$srcsi)
```

# Data for people with mixed modality
```{r mixed modality ids}
plf_data_baseline_mixed <- plf_data_baseline %>%
  filter(modality_type == 3)

# Number of sessions
table(
  plf_data_baseline_mixed$id,
  plf_data_baseline_mixed$n_sessions_attended
)

# Look at original sessions data for these folks
path <- "~/Labs/Github/project-life-force/project-life-force/Raw_datasets/database_12-29-2024.xlsx"
excel_sheets(path)

sessions <- read_excel(path, sheet = "sessions")
colnames(sessions) <- gsub("\\s+", "_", colnames(sessions))

# Make the 'total number of sessions attended' variable.
sessions <- sessions %>%
  group_by(id) %>%
  mutate(n_attended = if_else(arm == 1, sum(!is.na(date)), NA))

# Filter to mixed-modal
sessions_mixed <- sessions %>%
  filter(id %in% c("BX-074", "BX-084", "BX-087", "BX-089"))
sessions_mixed
```
